import { and, desc, eq, gte, lte, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { ENV } from "./_core/env";
import { InsertUser, users, products, customers, farmers, rateSlabs, invoices, invoiceItems, ledgerEntries, milkCollections, settings, payments } from "../drizzle/schema";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; for (const field of ["name", "email", "loginMethod"] as const) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } } values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn; if (user.role) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listProducts() { const db = await getDb(); return db ? db.select().from(products).where(eq(products.active, 1)).orderBy(products.name) : []; }
export async function listCustomers() { const db = await getDb(); return db ? db.select().from(customers).orderBy(customers.name) : []; }
export async function listFarmers() { const db = await getDb(); return db ? db.select().from(farmers).where(eq(farmers.active, 1)).orderBy(farmers.name) : []; }
export async function listRates() { const db = await getDb(); return db ? db.select().from(rateSlabs).where(eq(rateSlabs.active, 1)).orderBy(rateSlabs.minFat) : []; }
export async function listCollections(limit = 20) { const db = await getDb(); return db ? db.select().from(milkCollections).orderBy(desc(milkCollections.collectedAt)).limit(limit) : []; }
export async function listInvoices(limit = 20) { const db = await getDb(); return db ? db.select().from(invoices).orderBy(desc(invoices.createdAt)).limit(limit) : []; }
export async function getCustomerLedger(customerId: number) { const db = await getDb(); if (!db) return []; return db.select().from(ledgerEntries).where(eq(ledgerEntries.customerId, customerId)).orderBy(desc(ledgerEntries.createdAt)); }
export async function getInvoiceItems(invoiceId: number) { const db = await getDb(); if (!db) return []; return db.select().from(invoiceItems).where(eq(invoiceItems.invoiceId, invoiceId)); }
export async function getSettings() { const db = await getDb(); if (!db) return {}; const rows = await db.select().from(settings); return Object.fromEntries(rows.map(row => [row.settingKey, row.settingValue])); }
export async function getDashboard() { const db = await getDb(); if (!db) return { salesToday: 0, salesWeek: 0, salesMonth: 0, milkToday: 0, milkWeek: 0, milkMonth: 0, farmerPayoutsToday: 0, farmerPayoutsWeek: 0, farmerPayoutsMonth: 0, receivables: 0, lowStock: 0 }; const now = new Date(); const start = new Date(now); start.setHours(0, 0, 0, 0); const week = new Date(start); week.setDate(start.getDate() - 6); const month = new Date(now.getFullYear(), now.getMonth(), 1); const sum = async (table: any, field: any, since: Date) => { const result = await db!.select({ value: sql<string>`coalesce(sum(${field}),0)` }).from(table).where(gte(table.createdAt ?? table.collectedAt, since)); return Number(result[0]?.value ?? 0); }; const [salesToday, salesWeek, salesMonth, milkToday, milkWeek, milkMonth, payoutsToday, payoutsWeek, payoutsMonth, receivables, lowStock] = await Promise.all([sum(invoices, invoices.total, start), sum(invoices, invoices.total, week), sum(invoices, invoices.total, month), sum(milkCollections, milkCollections.quantityLiters, start), sum(milkCollections, milkCollections.quantityLiters, week), sum(milkCollections, milkCollections.quantityLiters, month), sum(milkCollections, milkCollections.amount, start), sum(milkCollections, milkCollections.amount, week), sum(milkCollections, milkCollections.amount, month), db.select({ value: sql<string>`coalesce(sum(case when ${ledgerEntries.type}='debit' then ${ledgerEntries.amount} else -${ledgerEntries.amount} end),0)` }).from(ledgerEntries).then(r => Number(r[0]?.value ?? 0)), db.select({ value: sql<number>`count(*)` }).from(products).where(and(eq(products.active, 1), lte(products.stockQuantity, products.lowStockThreshold))).then(r => Number(r[0]?.value ?? 0))]); return { salesToday, salesWeek, salesMonth, milkToday, milkWeek, milkMonth, farmerPayoutsToday: payoutsToday, farmerPayoutsWeek: payoutsWeek, farmerPayoutsMonth: payoutsMonth, receivables, lowStock }; }
export { products, customers, farmers, rateSlabs, invoices, invoiceItems, ledgerEntries, milkCollections, settings, payments };
