import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { z } from "zod";
import { desc, eq, sql } from "drizzle-orm";
import { getDb, getDashboard, getCustomerLedger, getInvoiceItems, getSettings, listCollections, listCustomers, listFarmers, listInvoices, listProducts, listRates, products, customers, farmers, rateSlabs, invoices, invoiceItems, ledgerEntries, milkCollections, settings, payments } from "./db";
import { invokeLLM } from "./_core/llm";
const money = z.coerce.number().nonnegative();
const unavailable = () => { throw new Error("Database unavailable"); };

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  dashboard: protectedProcedure.query(() => getDashboard()),
  assistant: router({ ask: protectedProcedure.input(z.object({ question: z.string().min(1), history: z.array(z.object({ role: z.enum(["user", "assistant"]), content: z.string() })).default([]) })).mutation(async ({ input }) => { const dashboard = await getDashboard(); const context = `Live business context: sales today ${dashboard.salesToday}, sales this week ${dashboard.salesWeek}, sales this month ${dashboard.salesMonth}, milk today ${dashboard.milkToday} L, milk this week ${dashboard.milkWeek} L, farmer payouts today ${dashboard.farmerPayoutsToday}, receivables ${dashboard.receivables}, low-stock products ${dashboard.lowStock}.`; const response = await invokeLLM({ messages: [{ role: "system", content: `You are Gajurmukhi Dairy's practical business assistant. Answer concisely, use Indian rupee formatting when useful, do not invent unavailable figures, and clearly say when a question requires a report that is not in the live context. ${context}` }, ...input.history, { role: "user", content: input.question }] }); const content = response.choices?.[0]?.message?.content; return { answer: typeof content === "string" ? content : "I could not prepare an answer right now." }; }) }),
  settings: router({ list: protectedProcedure.query(() => getSettings()), upsert: protectedProcedure.input(z.object({ key: z.string().min(1), value: z.string().min(1) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); await db.insert(settings).values({ settingKey: input.key, settingValue: input.value }).onDuplicateKeyUpdate({ set: { settingValue: input.value } }); return { success: true }; }) }),
  products: router({ list: protectedProcedure.query(() => listProducts()), create: protectedProcedure.input(z.object({ name: z.string().min(1), unit: z.string().min(1), price: money, stockQuantity: z.coerce.number().nonnegative(), lowStockThreshold: z.coerce.number().nonnegative().default(5) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); await db.insert(products).values({ ...input, price: input.price.toFixed(2), stockQuantity: input.stockQuantity.toFixed(3), lowStockThreshold: input.lowStockThreshold.toFixed(3) }); return { success: true }; }), update: protectedProcedure.input(z.object({ id: z.number(), name: z.string().min(1), unit: z.string().min(1), price: money, stockQuantity: z.coerce.number().nonnegative(), lowStockThreshold: z.coerce.number().nonnegative() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); const { id, ...data } = input; await db.update(products).set({ ...data, price: data.price.toFixed(2), stockQuantity: data.stockQuantity.toFixed(3), lowStockThreshold: data.lowStockThreshold.toFixed(3) }).where(eq(products.id, id)); return { success: true }; }) }),
  customers: router({ list: protectedProcedure.query(() => listCustomers()), create: protectedProcedure.input(z.object({ name: z.string().min(1), phone: z.string().optional(), openingBalance: money.default(0) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); await db.insert(customers).values({ ...input, openingBalance: input.openingBalance.toFixed(2) }); return { success: true }; }), ledger: protectedProcedure.input(z.object({ customerId: z.number() })).query(({ input }) => getCustomerLedger(input.customerId)), addEntry: protectedProcedure.input(z.object({ customerId: z.number(), type: z.enum(["debit", "credit"]), amount: money, reference: z.string().optional(), note: z.string().optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); await db.insert(ledgerEntries).values({ ...input, amount: input.amount.toFixed(2) }); return { success: true }; }), balance: protectedProcedure.input(z.object({ customerId: z.number() })).query(async ({ input }) => { const rows = await getCustomerLedger(input.customerId); return rows.reduce((sum, row) => sum + (row.type === "debit" ? Number(row.amount) : -Number(row.amount)), 0); }) }),
  farmers: router({ list: protectedProcedure.query(() => listFarmers()), create: protectedProcedure.input(z.object({ name: z.string().min(1), phone: z.string().optional(), village: z.string().optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); await db.insert(farmers).values(input); return { success: true }; }) }),
  rates: router({ list: protectedProcedure.query(() => listRates()), create: protectedProcedure.input(z.object({ name: z.string().min(1), minFat: z.coerce.number(), maxFat: z.coerce.number(), minSnf: z.coerce.number(), maxSnf: z.coerce.number(), ratePerLiter: money })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); await db.insert(rateSlabs).values({ ...input, minFat: input.minFat.toFixed(2), maxFat: input.maxFat.toFixed(2), minSnf: input.minSnf.toFixed(2), maxSnf: input.maxSnf.toFixed(2), ratePerLiter: input.ratePerLiter.toFixed(2) }); return { success: true }; }), update: protectedProcedure.input(z.object({ id: z.number(), name: z.string().min(1), minFat: z.coerce.number(), maxFat: z.coerce.number(), minSnf: z.coerce.number(), maxSnf: z.coerce.number(), ratePerLiter: money })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); const { id, ...data } = input; await db.update(rateSlabs).set({ ...data, minFat: data.minFat.toFixed(2), maxFat: data.maxFat.toFixed(2), minSnf: data.minSnf.toFixed(2), maxSnf: data.maxSnf.toFixed(2), ratePerLiter: data.ratePerLiter.toFixed(2) }).where(eq(rateSlabs.id, id)); return { success: true }; }), remove: protectedProcedure.input(z.object({ id: z.number() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); await db.update(rateSlabs).set({ active: 0 }).where(eq(rateSlabs.id, input.id)); return { success: true }; }) }),
  collections: router({ list: protectedProcedure.query(() => listCollections()), create: protectedProcedure.input(z.object({ farmerId: z.number(), session: z.enum(["morning", "evening"]), quantityLiters: z.coerce.number().positive(), fat: z.coerce.number().positive(), snf: z.coerce.number().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); const slabs = await listRates(); const slab = slabs.find(s => input.fat >= Number(s.minFat) && input.fat <= Number(s.maxFat) && input.snf >= Number(s.minSnf) && input.snf <= Number(s.maxSnf)); if (!slab) throw new Error("No active rate slab matches these FAT/SNF readings"); const rate = Number(slab.ratePerLiter); const amount = rate * input.quantityLiters; await db.insert(milkCollections).values({ ...input, quantityLiters: input.quantityLiters.toFixed(3), fat: input.fat.toFixed(2), snf: input.snf.toFixed(2), ratePerLiter: rate.toFixed(2), amount: amount.toFixed(2) }); return { success: true, rate, amount }; }) }),
  invoices: router({ list: protectedProcedure.query(() => listInvoices()), items: protectedProcedure.input(z.object({ invoiceId: z.number() })).query(({ input }) => getInvoiceItems(input.invoiceId)), create: protectedProcedure.input(z.object({ customerId: z.number().optional(), discount: money.default(0), paid: money.default(0), paymentMode: z.enum(["cash", "qr", "bank", "credit"]), items: z.array(z.object({ productId: z.number(), productName: z.string(), quantity: z.coerce.number().positive(), unitPrice: money })).min(1) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) return unavailable(); const subtotal = input.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const total = Math.max(0, subtotal - input.discount); const paid = Math.min(input.paid, total); const due = Math.max(0, total - paid); const invoiceNumber = `GDS-${Date.now().toString().slice(-8)}`; const status = due > 0 ? "pending" : "paid"; for (const item of input.items) { const row = await db.select().from(products).where(eq(products.id, item.productId)).limit(1); if (!row[0] || Number(row[0].stockQuantity) < item.quantity) throw new Error(`${item.productName} does not have enough stock`); } await db.insert(invoices).values({ invoiceNumber, customerId: input.customerId, subtotal: subtotal.toFixed(2), discount: input.discount.toFixed(2), total: total.toFixed(2), paid: paid.toFixed(2), due: due.toFixed(2), paymentMode: input.paymentMode, status }); const created = await db.select({ id: invoices.id }).from(invoices).where(eq(invoices.invoiceNumber, invoiceNumber)).limit(1); const invoiceId = created[0]?.id; if (!invoiceId) throw new Error("Invoice creation failed"); await db.insert(invoiceItems).values(input.items.map(item => ({ invoiceId, productId: item.productId, productName: item.productName, quantity: item.quantity.toFixed(3), unitPrice: item.unitPrice.toFixed(2), lineTotal: (item.quantity * item.unitPrice).toFixed(2) }))); for (const item of input.items) await db.update(products).set({ stockQuantity: sql`${products.stockQuantity} - ${item.quantity}` }).where(eq(products.id, item.productId)); await db.insert(payments).values({ invoiceId, customerId: input.customerId, amount: paid.toFixed(2), mode: input.paymentMode, reference: invoiceNumber }); if (input.customerId && due > 0) await db.insert(ledgerEntries).values({ customerId: input.customerId, type: "debit", amount: due.toFixed(2), reference: invoiceNumber, note: "Retail invoice due" }); return { success: true, invoiceId, invoiceNumber, total, paid, due }; }) }),
});
export type AppRouter = typeof appRouter;
